title: a title
author: me
email: your-email@domain.com
description: > no description for no content

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
